#! /bin/sh

# This script shows all the plots in the current working directory.
# The script takes one optional argument, which is either
# the integer `0` to enable interactive plots
# that do not update automatically or
# the positive integer `n` to enable noninteractive plots
# that update automatically every `n` seconds.

case "$#" in
  0)
    t=0
    ;;
  1)
    t="$1"
    ;;
  *)
    echo "Too many arguments." >&2
    exit 1
    ;;
esac

s='EXIT HUP INT QUIT PIPE TERM' && \
trap wait CONT && \
d=$(mktemp -d) && \
trap 'trap - $s && rm -fr "$d" && kill -- "-$$" 2> /dev/null' $s && \
for x in *.gp
do
  ( y="$d/$(basename "$x")" && \
    { echo 'set terminal wxt noraise' && \
      sed '/^set \(terminal\|output\)/d' "$x" && \
      if test "$t" -gt 0
      then
        echo "pause $t" && \
        echo reread
      else
        echo 'pause mouse close'
      fi
    } > "$y" && \
    gnuplot "$y" 2> /dev/null
  ) &
done && \
wait
